"""
## Overview
This file contains the schema definitions for request and response models used in the application.
The schemas are implemented using Pydantic's `BaseModel` to ensure data validation and serialization.
The file includes base schemas, error response schemas, and specific schemas for processing invoices and invoice details.
"""

from typing import List, Optional

from pydantic import BaseModel, Field

from constants import Environments
from utils import get_current_datetime_cst


class Requests:
    # Base Request Schema
    class BaseRequest(BaseModel):
        """
        Base Request Schema

        Attributes:
            api_request_uuid (str): Unique identifier for the request to store in cosmos.
        """

        # Autogenerated id for cosmos api logging, will be added by the middleware/decorator automatically
        api_request_uuid: Optional[str] = None

    class ProcessRequest(BaseRequest):
        """
        Base Request Schema for all processing requests

        Attributes:
            id (str): Unique identifier for the request.
        """

        id: str

    # Process All Invoices Request Schema
    class ProcessAllInvoicesRequest(ProcessRequest):
        """
        Request Schema for processing all invoices.

        Inherits:
            ProcessRequest: Base request schema.
        """

    # Process Invoice Request Schema
    class ProcessInvoiceRequest(ProcessRequest):
        """
        Request Schema for processing a single invoice.

        Attributes:
            invoice_id (str): Unique identifier for the invoice to be processed.

        Inherits:
            ProcessRequest: Base request schema.
        """

        invoice_id: str

    # Process Invoice Detail Request Schema
    class ProcessInvoiceDetailRequest(ProcessRequest):
        """
        Request Schema for processing invoice details.

        Attributes:
            invoice_detail_ids (List[int]): List of unique identifiers for invoice details to be processed.
            classify (Optional[bool]): Flag indicating whether to classify the invoice details. Defaults to True.
            local_test (Optional[bool]): Flag indicating whether to perform a local test. Defaults to False.

        Inherits:
            ProcessRequest: Base request schema.
        """

        invoice_detail_ids: List[int]
        classify: Optional[bool] = True
        local_test: Optional[bool] = False
        sys_name: Optional[str] = Environments.WEB

    # Reload App Config Request Schema
    class ReloadAppConfigRequest(BaseRequest):
        """
        Request Schema for processing a single invoice.

        Attributes:
            invoice_id (str): Unique identifier for the invoice to be processed.

        Inherits:
            BaseRequest: Base request schema.
        """

    class GetConfigSnapshotRequest(BaseRequest):
        """
        Request Schema for get config snapshot.

        Inherits:
            BaseRequest: Base request schema.
        """

    # Process All Invoices Request Schema
    class GetWorkerStatusRequest(BaseRequest):
        """
        Request Schema for fetching worker status.

        Inherits:
            BaseRequest: Base request schema.
        """


class Responses:
    # Base Response Schema
    class BaseResponse(BaseModel):
        """
        Base Response Schema

        Attributes:
            status (str): Status of the response (e.g., success, failure).
            message (Optional[str]): Optional message providing additional information about the response.
        """

        status: str
        message: Optional[str] = None
        repliedAt: Optional[str] = Field(default_factory=get_current_datetime_cst)

    # Error Response Schema
    class ErrorResponse(BaseResponse):
        """
        Error Response Schema

        Attributes:
            error_detail (Optional[str]): Optional detailed error message or description.
        """

        error_detail: Optional[str] = None

    class ProcessResponse(BaseResponse):
        """
        Base Response Schema for all processing requests

        Attributes:
            replyToId (str): Identifier of the request this response is replying to.
        """

        replyToId: str

    # Process All Invoices Response Schema
    class ProcessAllInvoicesResponse(ProcessResponse):
        """
        Response Schema for processing all invoices.

        Inherits:
            ProcessResponse: Base response schema.
        """

    # Process Invoice Response Schema
    class ProcessInvoiceResponse(ProcessResponse):
        """
        Response Schema for processing a single invoice.

        Inherits:
            ProcessResponse: Base response schema.
        """

    # Process Invoice Detail Response Schema
    class ProcessInvoiceDetailResponse(ProcessResponse):
        """
        Response Schema for processing invoice details.

        Inherits:
            ProcessResponse: Base response schema.
        """

    # Reload App Config Response Schema
    class ReloadAppConfigResponse(BaseResponse):
        """
        Response Schema for processing invoice details.

        Inherits:
            BaseResponse: Base response schema.
        """

    # Reload App Config Response Schema
    class GetConfigSnapshotResponse(BaseResponse):
        """
        Response Schema for get config snapshot.

        Inherits:
            BaseResponse: Base response schema.
        """

        config: dict

    # Reload App Config Response Schema
    class GetWorkerStatusResponse(BaseResponse):
        """
        Response Schema for fetching worker status.

        Inherits:
            BaseResponse: Base response schema.
        """

        supervisor: bool
        worker: bool
