
select * from SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL ORDER BY PRNT_CTGY_ID, CTGY_ID

INSERT INTO SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL
  (CTGY_ID, CTGY_NM, REC_CRTD_DTTM, REC_UPDD_DTTM, REC_CRTD_BY_ID, REC_UPDD_BY_ID)
VALUES
  ('8', 'DISCOUNTS', GETDATE(), GETDATE(), 'AI_USER', 'AI_USER')

INSERT INTO SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL
  (CTGY_ID, CTGY_NM, PRNT_CTGY_ID, REC_CRTD_DTTM, REC_UPDD_DTTM, REC_CRTD_BY_ID, REC_UPDD_BY_ID)
SELECT v.CTGY_ID, v.CTGY_NM, v.PRNT_CTGY_ID, GETDATE(), GETDATE(), 'AI_USER', 'AI_USER'
FROM (VALUES
    ('6.2', 'FREIGHT', '6'),
    ('6.3', 'LABOR', '6'),
    ('6.4', 'FEE', '6'),
    ('6.5', 'TAX', '6'),
    ('6.8', 'DISCOUNTS', '6')
) AS v (CTGY_ID, CTGY_NM, PRNT_CTGY_ID)
WHERE NOT EXISTS (
    SELECT 1
    FROM SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL t
    WHERE t.CTGY_ID = v.CTGY_ID
);


INSERT INTO SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL
  (CTGY_ID, CTGY_NM, PRNT_CTGY_ID, REC_CRTD_DTTM, REC_UPDD_DTTM, REC_CRTD_BY_ID, REC_UPDD_BY_ID)
SELECT v.CTGY_ID, v.CTGY_NM, v.PRNT_CTGY_ID, GETDATE(), GETDATE(), 'AI_USER', 'AI_USER'
FROM (VALUES
    ('6.1.2', 'GENERIC', '6.1'),
    ('6.1.1', 'LOT', '6.1')
) AS v (CTGY_ID, CTGY_NM, PRNT_CTGY_ID)
WHERE NOT EXISTS (
    SELECT 1
    FROM SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL t
    WHERE t.CTGY_ID = v.CTGY_ID
);

Update SDPDWH.AIML.IVCE_XCTN_CLSFR_CTGY_DTL set CTGY_NM = 'MATERIAL' WHERE CTGY_ID = '6.1'
