
SELECT MFR_NM, CLN_MFR_NM, AI_MCH_IND FROM SDPDWH.RPAO.MFR_DTL
WHERE CLN_MFR_NM IN ('TAX', 'FEE', 'FREIGHT', 'LABOR', 'LOT', 'DISCOUNTS', 'BAD', 'UNCLASSIFIED', 'MATERIAL')

SELECT DISTINCT AI_MCH_IND FROM SDPDWH.RPAO.MFR_DTL

INSERT INTO SDPDWH.RPAO.MFR_DTL
  (MFR_NM, CLN_MFR_NM, AI_MCH_IND, REC_CRTD_BY_ID, REC_UPDD_BY_ID, REC_CRTD_DTTM, REC_UPDD_DTTM)
VALUES
  ('DISCOUNTS', 'DISCOUNTS', 'N', 'AI_USER', 'AI_USER', GETDATE(), GETDATE())

INSERT INTO SDPDWH.RPAO.MFR_DTL
  (MFR_NM, CLN_MFR_NM, AI_MCH_IND, REC_CRTD_BY_ID, REC_UPDD_BY_ID, REC_CRTD_DTTM, REC_UPDD_DTTM)
VALUES
  ('LOT', 'LOT', 'N', 'AI_USER', 'AI_USER', GETDATE(), GETDATE())

INSERT INTO SDPDWH.RPAO.MFR_DTL
  (MFR_NM, CLN_MFR_NM, AI_MCH_IND, REC_CRTD_BY_ID, REC_UPDD_BY_ID, REC_CRTD_DTTM, REC_UPDD_DTTM)
VALUES
  ('UNCLASSIFIED', 'UNCLASSIFIED', 'N', 'AI_USER', 'AI_USER', GETDATE(), GETDATE())

DELETE FROM SDPDWH.RPAO.MFR_DTL WHERE CLN_MFR_NM = 'DISCOUNTS' AND AI_MCH_IND IS NULL
