USE [SDPDWH]

-- CREATE SCHEMA [AIML] AUTHORIZATION db_owner;

CREATE TABLE [AIML].[IVCE_XCTN_LLM_TRNL_MFR_REF] (
    [IVCE_XCTN_LLM_TRNL_MFR_REF_UID] [int] IDENTITY(1,1) NOT NULL,
    [AKS_PRT_NUM] VARCHAR(50) NULL,
    [MFR_PRT_NUM] VARCHAR(50) NOT NULL,
    [MFR_NM] VARCHAR(100) NOT NULL,
    [UPC_CD] VARCHAR(20) NOT NULL,
    [UNSPSC_CD] VARCHAR(20) NOT NULL,
    [REC_CRTD_BY_ID] VARCHAR(20) NULL,
    [REC_CRTD_DTTM] DATETIME NULL,
    [REC_UPDD_BY_ID] VARCHAR(20) NULL,
    [REC_UPDD_DTTM] DATETIME NULL,
	CONSTRAINT [PK_IVCE_XCTN_LLM_TRNL_MFR_REF] PRIMARY KEY CLUSTERED
	(
	[IVCE_XCTN_LLM_TRNL_MFR_REF_UID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
    ON [PRIMARY]
	) ON [PRIMARY]

CREATE NONCLUSTERED INDEX IX_MFR_PRT_NUM
    ON AIML.IVCE_XCTN_LLM_TRNL_MFR_REF (MFR_PRT_NUM);

CREATE TABLE [AIML].[IVCE_XCTN_LLM_TRNL_PRDT_REF] (
    IVCE_XCTN_LLM_TRNL_PRDT_REF_UID [int] IDENTITY(1,1) NOT NULL,
    IVCE_XCTN_LLM_TRNL_MFR_REF_UID [int] NOT NULL,
    SRC_NM VARCHAR(100) NULL,
    SRC_REC_ID VARCHAR(20) NULL,
    IVCE_PRDT_LDSC VARCHAR(2000) NOT NULL,
    TRNG_DAT_VRSN_NUM VARCHAR(50) NOT NULL,
    REC_ACTV_IND VARCHAR(1) NOT NULL,
    REC_CRTD_BY_ID VARCHAR(20) NULL,
    REC_CRTD_DTTM DATETIME NULL,
    REC_UPDD_BY_ID VARCHAR(20) NULL,
    REC_UPDD_DTTM DATETIME NULL,
    CONSTRAINT [PK_IVCE_XCTN_LLM_TRNL_PRDT_REF] PRIMARY KEY CLUSTERED
	(
	[IVCE_XCTN_LLM_TRNL_PRDT_REF_UID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
	ON [PRIMARY],
	CONSTRAINT [FK_IVCE_XCTN_LLM_TRNL_PRDT_REF_MFR] FOREIGN KEY
	(
		[IVCE_XCTN_LLM_TRNL_MFR_REF_UNQ_ID])
        REFERENCES [AIML].[IVCE_XCTN_LLM_TRNL_MFR_REF] ([IVCE_XCTN_LLM_TRNL_MFR_REF_UID])
        ON DELETE CASCADE
        ON UPDATE CASCADE
	) ON [PRIMARY];


CREATE TABLE [AIML].[IVCE_XCTN_CLSFR_TRNL_DESC_REF] (
    IVCE_XCTN_CLSFR_TRNL_DESC_REF_UID [int] IDENTITY(1,1) NOT NULL,
    IVCE_PRDT_LDSC VARCHAR(2000) NOT NULL,
    CLS_NM VARCHAR(20) NOT NULL,
    TRNG_DAT_VRSN_NUM VARCHAR(50) NOT NULL,
    REC_ACTV_IND VARCHAR(1) NOT NULL,
    REC_CRTD_BY_ID VARCHAR(20) NULL,
    REC_CRTD_DTTM DATETIME NULL,
    REC_UPDD_BY_ID VARCHAR(20) NULL,
    REC_UPDD_DTTM DATETIME NULL,
    CONSTRAINT [PK_IVCE_XCTN_CLSFR_TRNL_DESC_REF] PRIMARY KEY CLUSTERED
	(
	[IVCE_XCTN_CLSFR_TRNL_DESC_REF_UID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
	ON [PRIMARY]
	) ON [PRIMARY];

-- Classifier and Subclassifier table.
CREATE TABLE [AIML].[IVCE_XCTN_CLSFR_CTGY_DTL] (
    [IVCE_XCTN_CLSFR_CTGY_DTL_UID] [int] IDENTITY(1,1) NOT NULL,
    [CTGY_ID] VARCHAR(20) NOT NULL UNIQUE,
    [CTGY_NM] VARCHAR(100) NOT NULL,
    [PRNT_CTGY_ID] VARCHAR(20) NULL,
    [REC_CRTD_BY_ID] VARCHAR(20) NULL,
    [REC_CRTD_DTTM] DATETIME NULL,
    [REC_UPDD_BY_ID] VARCHAR(20) NULL,
    [REC_UPDD_DTTM] DATETIME NULL,
	CONSTRAINT [PK_IVCE_XCTN_CLSFR_CTGY_DTL] PRIMARY KEY CLUSTERED
	(
	[IVCE_XCTN_CLSFR_CTGY_DTL_UID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
    ON [PRIMARY],

    CONSTRAINT [FK_IVCE_XCTN_CLSFR_CTGY_DTL_PRNT_CTGY_ID] FOREIGN KEY
	(
		[PRNT_CTGY_ID])
		REFERENCES [AIML].[IVCE_XCTN_CLSFR_CTGY_DTL] ([CTGY_ID])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
) ON [PRIMARY];
